---
- name: Install if enabled
  when:
    - elasticsearch_curator_enabled
  tags:
    - elasticsearch-curator
  block:
    - name: Install required packages
      loop:
        - python3-pip
        - python3-virtualenv
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      tags:
        - elasticsearch-curator

    - name: Install elasticsearch lib
      when:
        - false if elasticsearch_curator_library is none else (elasticsearch_curator_library | length > 0)
      ansible.builtin.pip:
        name: elasticsearch
        state: present
        version: "{{ elasticsearch_curator_library }}"
        virtualenv: "{{ elasticsearch_curator_venv_path }}"
      tags:
        - elasticsearch-curator

    - name: Install curator package
      ansible.builtin.pip:
        name: elasticsearch-curator
        state: present
        version: "{{ elasticsearch_curator_version }}"
        virtualenv: "{{ elasticsearch_curator_venv_path }}"
      tags:
        - elasticsearch-curator

    - name: Symlink venv executable
      ansible.builtin.file:
        src: "{{ elasticsearch_curator_venv_path }}/bin/curator"
        dest: /usr/local/bin/curator
        state: link
        force: true
      tags:
        - elasticsearch-curator

    - name: Create config directory
      ansible.builtin.file:
        path: /root/.curator
        owner: root
        group: root
        mode: u=rwX,g=rX,o=
        state: directory
      tags:
        - elasticsearch-curator

    - name: Write general config
      notify:
        - Restart curator
      ansible.builtin.template:
        src: config.j2
        dest: /root/.curator/curator.yml
        owner: root
        group: root
        mode: u=rw,g=r,o=
      tags:
        - elasticsearch-curator

    - name: Write actions config
      notify:
        - Restart curator
      ansible.builtin.template:
        src: actions.j2
        dest: /root/.curator/actions.yml
        owner: root
        group: root
        mode: u=rw,g=r,o=
      tags:
        - elasticsearch-curator

    - name: Write timer file
      notify:
        - Restart curator
      ansible.builtin.template:
        src: timer.j2
        dest: /etc/systemd/system/curator.timer
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      tags:
        - elasticsearch-curator

    - name: Write service file
      notify:
        - Restart curator
      ansible.builtin.template:
        src: service.j2
        dest: /etc/systemd/system/curator.service
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      tags:
        - elasticsearch-curator

    - name: Start curator timer
      ansible.builtin.systemd:
        name: curator.timer
        state: started
        daemon_reload: true
        masked: false
        enabled: true
      tags:
        - elasticsearch-curator

...
