---
- name: Install if enabled
  when: elasticsearch_curator_enabled
  tags:
    - elasticsearch-curator
  block:
    - name: Install pip package
      ansible.builtin.package:
        name: python3-pip
        state: present
      tags:
        - elasticsearch-curator

    - name: Install elasticsearch pip
      when: elasticsearch_curator_library | default(False)
      ansible.builtin.pip:
        name: elasticsearch
        state: present
        version: "{{ elasticsearch_curator_library }}"
      tags:
        - elasticsearch-curator

    - name: Install curator pip
      ansible.builtin.pip:
        name: elasticsearch-curator
        state: present
        version: "{{ elasticsearch_curator_version }}"
      tags:
        - elasticsearch-curator

    - name: Create config directory
      ansible.builtin.file:
        path: /root/.curator
        owner: root
        group: root
        mode: u=rwX,g=rX,o=
        state: directory
      tags:
        - elasticsearch-curator

    - name: Write general config
      notify:
        - Restart curator
      ansible.builtin.template:
        src: config.j2
        dest: /root/.curator/curator.yml
        owner: root
        group: root
        mode: u=rw,g=r,o=
      tags:
        - elasticsearch-curator

    - name: Write actions config
      notify:
        - Restart curator
      ansible.builtin.template:
        src: actions.j2
        dest: /root/.curator/actions.yml
        owner: root
        group: root
        mode: u=rw,g=r,o=
      tags:
        - elasticsearch-curator

    - name: Write timer file
      notify:
        - Restart curator
      ansible.builtin.template:
        src: timer.j2
        dest: /etc/systemd/system/curator.timer
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      tags:
        - elasticsearch-curator

    - name: Write service file
      notify:
        - Restart curator
      ansible.builtin.template:
        src: service.j2
        dest: /etc/systemd/system/curator.service
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      tags:
        - elasticsearch-curator

    - name: Start curator timer
      ansible.builtin.systemd:
        name: curator.timer
        state: started
        daemon_reload: True
        masked: False
        enabled: True
      tags:
        - elasticsearch-curator

...
