---
- name: Restart curator
  loop: "{{ ['timer', 'service'] if elasticsearch_curator_restart_service else ['timer'] }}"
  ansible.builtin.systemd:
    name: "curator.{{ item }}"
    state: restarted
    daemon_reload: true

...
